# How to calculate the hypervolume metric

In [ ]:
# %pip install pygmo
# %pip list

## How to calculate hypervolume??

In [2]:
import pygmo as pg

# Construct a DTLZ-2 problem with 3-dimensional fitness space and 10 dimensions

hv = pg.hypervolume([[1, 0], [0.5, 0.5], [0, 1], [1.5, 0.75]] )

ref_point = [2,2]

hv.compute(ref_point)

3.25

In [6]:
import pandas as pd

In [19]:
# %ls src/cpp/build

filepath = "src/cpp/build/nsgaii_A-n50-m4-Q80_20220626213806.csv"

# df = pd.read_csv(filepath, sep=';', )
# df = pd.read_csv(filepath)
df = pd.read_csv(filepath, sep=';', skiprows=1)
df.head()

,9,10,46,42,12,35,44,20,39,17,...,37,49,11,29,48,26,3,"58,3953",-137,
0,28,49,36,14,10,18,8,35,47,42,...,13,46,3,12,40,48,32,"205,71",-407,
1,47,15,13,12,6,42,14,20,16,0,...,40,29,48,45,1,11,46,"114,953",-323,
2,28,49,36,14,10,26,8,35,39,42,...,17,46,3,12,40,48,43,"190,396",-383,
3,3,30,28,12,47,31,6,20,16,0,...,48,29,33,10,1,11,46,"132,84",-325,
4,3,7,24,12,31,38,14,5,32,43,...,40,29,33,49,1,11,46,"89,1145",-262,

In [17]:
df

                                                                                                                                                                    x, f
9  10 46 42 12 35 44 20 39 17 31 15 21 25 6  47 40 27 36 32 4  22 33 43 34 16 38 18 41 14 5  0  23 30 24 1  13 2  19 7  28 8  45 37 49 11 29 48 26 3   58,3953 -137
28 49 36 14 10 18 8  35 47 42 0  6  9  23 25 38 37 16 31 43 2  22 5  4  20 39 44 26 41 24 45 19 1  11 34 33 29 15 21 27 7  30 17 13 46 3  12 40 48 32  205,71  -407
47 15 13 12 6  42 14 20 16 0  10 21 4  26 35 39 34 43 23 31 9  7  41 37 32 49 3  44 38 30 22 18 36 25 5  28 19 2  27 8  33 17 24 40 29 48 45 1  11 46  114,953 -323
28 49 36 14 10 26 8  35 39 42 0  6  34 23 25 38 44 16 31 37 47 22 5  4  20 2  32 18 41 24 45 9  1  11 19 33 29 15 21 27 7  30 13 17 46 3  12 40 48 43  190,396 -383
3  30 28 12 47 31 6  20 16 0  49 18 4  26 35 43 34 39 23 5  38 15 36 24 32 42 9  44 45 2  21 22 41 25 14 13 19 7  27 8  40 17 37 48 29 33 10 1  11 46  132,84  -325
...                                                                                                                                                                  ...
9  10 46 42 12 35 44 20 39 17 31 15 21 25 6  47 40 27 36 32 4  22 33 43 34 16 38 18 41 14 5  0  23 30 24 1  13 2  19 7  28 8  45 37 49 11 29 48 26 3   58,3953 -137
47 8  28 12 31 20 3  45 16 0  10 32 4  26 35 43 34 39 23 6  9  15 41 37 21 42 14 44 38 2  22 18 36 25 5  13 19 30 27 7  33 49 24 40 29 48 17 46 11 1   174,034 -365
28 49 36 14 10 26 8  35 39 42 0  6  34 23 25 38 44 16 31 43 47 22 5  4  20 2  32 18 41 24 45 9  1  11 19 33 29 15 21 27 7  30 13 17 46 3  12 40 48 37  186,286 -382
47 15 28 12 6  20 44 49 16 0  10 21 41 26 35 39 34 43 23 31 9  7  4  37 32 42 3  14 38 2  22 18 36 25 5  13 1  30 27 8  33 17 24 40 29 48 45 19 11 46  146,174 -348
3  7  28 5  31 20 14 18 46 0  23 24 4  33 38 32 30 39 6  16 35 15 41 10 42 43 36 44 49 2  9  27 25 47 12 13 22 34 21 8  48 40 1  45 29 26 19 37 11 17  80,1132 -227

[100 rows x 1 columns]

In [34]:
import csv

list = []
with open(filepath, mode='r') as f:
    reader = csv.reader(f, delimiter=';')
    i = 0
    for line in reader:
        if i > 0:
            list.append([float(el.strip().replace(',', '.')) for el in line if el != ' '][-2:])
        i = i + 1

In [94]:
import os 

folderpath = 'src/cpp/build/'

results_map = {}
for file in os.listdir(folderpath):
    filepath = os.path.join(folderpath, file)
    list = []
    
    if os.path.isfile(filepath) and ('nsgaii' in file):
        with open(filepath, mode='r') as f:
            reader = csv.reader(f, delimiter=';')
            i = 0
            for line in reader:
                if i > 0:
                    list.append([float(el.strip().replace(',', '.')) for el in line if el != ' '][-2:])
                i = i + 1
        results_map[file] = list

all_results = {key:results_map[key] for key in results_map if len(results_map[key]) > 0}
all_results.keys()

dict_keys(['nsgaii_A-n50-m4-Q80.csv', 'nsgaii_A-n50-m4-Q80_20220626213806.csv', 'nsgaii_A-n50-m4-Q80_20220627114753.csv', 'nsgaii_A-n50-m4-Q80_20220627101403.csv', 'nsgaii_A-n50-m4-Q80_20220627095840.csv', 'nsgaii_A-n50-m4-Q80_20220627114935.csv', 'nsgaii_A-n50-m4-Q80_20220627095720.csv', 'nsgaii_A-n50-m4-Q80_20220627114431.csv'])

In [96]:
all_pop = []

for key in all_results:
    all_pop.extend(all_results[key])
#     print(len(all_results[key]))

len(all_pop)

700

In [99]:
import numpy as np

hv = pg.hypervolume(all_pop)

# hv.compute()

ref_point = hv.refpoint(offset=10)
ref_point

print(f"FILE\t\t RESULT")
for key in all_results:
    hv = pg.hypervolume(all_results[key])
    s_metric = hv.compute(ref_point)
    
    print(f"{key}\t\t{s_metric}")

FILE		 RESULT
nsgaii_A-n50-m4-Q80.csv		67080.33730000001
nsgaii_A-n50-m4-Q80_20220626213806.csv		65845.2598
nsgaii_A-n50-m4-Q80_20220627114753.csv		99609.51160000003
nsgaii_A-n50-m4-Q80_20220627101403.csv		93336.47570000002
nsgaii_A-n50-m4-Q80_20220627095840.csv		86330.73140000002
nsgaii_A-n50-m4-Q80_20220627114935.csv		94595.43990000003
nsgaii_A-n50-m4-Q80_20220627095720.csv		61318.61750000001
nsgaii_A-n50-m4-Q80_20220627114431.csv		91928.03330000002